services:
  - type: web
    name: digital-lung
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: lungtwin
      - key: CORS_ORIGINS
        sync: false
